### ISSUE TITLE
Swift 4.0+

### ISSUE THREAD

**Issue by robert-cronin** [kmcgill88/KMKeys-iOS#7]
Hi I am getting a few errors associated with instance methods not being exposed to objective-c and other errors that are associated with the difference between swift 3.x and swift 4.x such as "NSFontAttributeName has been renamed to NSAttributedStringKey"

Will this pod ever be adapted to swift 4.0?

**Comment by kmcgill88** [comment]
It should be! I haven't had a chance to upgrade it. PR's are welcome, otherwise I will get to it as time allows.

**Comment by robert-cronin** [comment]
Thank Kevin, I'm taking a look now, if all goes well you should see a PR in about an hour

**Comment by kmcgill88** [comment]
Awesome! [This fix](https://github.com/kmcgill88/McPicker-iOS/pull/19) on another project might be related.

**Comment by kmcgill88** [comment]
A little slow but I finally published `1.0.0`, updated for swift 4. Thanks!

**Comment by robert-cronin** [comment]
Nice! Let me know if there is anything else I can help with
